### ISSUE TITLE
Clean up Public & Private API

### ISSUE THREAD

**Issue by jamesnw** [oddbird/slide-deck#14]
**Describe the bug**

Currently, most of the methods are public, meaning the host could call things like `document.getElementsByTagName('slide-deck')[0].appendShadowTemplate()`, which is not needed, and throws an error.

A limited number of methods and values could be useful to expose, for instance-

- activeSlide
- startPresentation
- goTo

We probably want to move the majority to private, and then intentionally expose and document a select few.

**Comment by mirisuzanne** [comment]
I think I started changing this in one of the PRs…
