### ISSUE TITLE
Keyboard shortcuts not working on Windows

### ISSUE THREAD

**Issue by jerivas** [oddbird/slide-deck#17]
**Describe the bug**
I'm unable to pull up the control panel in Windows. In fact, all of these don't work:

- command-k: Toggle control panel
- command-shift-enter: Start presentation (from first slide)
- command-enter: Resume presentation (from active slide)
- command-shift-f: Toggle full-screen mode
- command-.: End presentation

**To Reproduce**
Open the demo site in Windows and try any of the shortcuts above. Nothing happens

**Expected behaviour**
The action associated with each shortcut happens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Edge, and Firefox

**Comment by jerivas** [comment]
I'm assuming in Windows `command` should be replaced by `ctrl`. Is that right?

**Comment by mirisuzanne** [comment]
Maybe? Mac has both, and I thought windows did too? It sounds to me like we should maybe re-open #3 and make sure we have a proposed set of shortcuts that work everywhere.

**Comment by jerivas** [comment]
Windows keyboards don't have Cmd; just Ctrl, Alt, Shift and the Windows key (also called Super in Linux). I would expect Ctrl to work in Windows as Cmd does in Mac, that's how I've always seen apps do it

**Comment by jerivas** [comment]
For context: here are the shortcuts for [Windows](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) and [Mac](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) for VS Code

**Comment by mirisuzanne** [comment]
Sounds good to me. Something you want to implement?

**Comment by jerivas** [comment]
Yep, will do 👍

**Comment by jerivas** [comment]
Shortcuts discussion in this issue: https://github.com/oddbird/slide-deck/issues/3
