### ISSUE TITLE
Allow slide view setting as part of URL

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/slide-deck#34]
**Is your feature request related to a problem? Please describe.**

It's useful sometimes to link to a slide deck already in a particular view.

**Describe the solution you'd like**

Maybe we could update a query param when setting the view, and use that when we load a link? I don't know how we'd want that to interact with the attribute…

**Comment by mirisuzanne** [comment]
My instinct is that:

- The url param, when set, is the source of truth
- When there's no url param, we check sessionStorage
- When there's no sessionStorage, we use the HTML attribute

@jamesnw @stacyk does that sound right to you?

**Comment by jamesnw** [comment]
I think that's correct. I assume we'll update the url param if the user changes the view?
